base_images:
  os:
    name: centos
    namespace: origin
    tag: stream8
  operator-sdk:
    name: "4.13"
    namespace: origin
    tag: operator-sdk
  previous-bundle:
    name: opendatahub-operator-bundle
    namespace: opendatahub-operator-upgrade
    tag: opendatahub-operator-bundle
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
images:
- build_args:
  - name: MANIFEST_RELEASE
    value: master
  context_dir: .
  dockerfile_path: Dockerfiles/Dockerfile
  from: os
  to: opendatahub-operator
operator:
  bundles:
  - as: odho-bundle
    dockerfile_path: Dockerfiles/bundle.Dockerfile
  substitutions:
  - pullspec: REPLACE_IMAGE:latest
    with: pipeline:opendatahub-operator
promotion:
  to:
  - additional_images:
      opendatahub-operator-bundle: odho-bundle
    name: opendatahub-operator-bundle-latest
    namespace: opendatahub-operator-upgrade
releases:
  initial:
    integration:
      name: "4.13"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.13"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
tests:
- as: opendatahub-operator-pr-image-mirror
  steps:
    dependencies:
      SOURCE_IMAGE_REF: opendatahub-operator
    env:
      IMAGE_REPO: opendatahub-operator
    workflow: opendatahub-io-ci-image-mirror
- as: opendatahub-operator-image-mirror
  postsubmit: true
  steps:
    dependencies:
      SOURCE_IMAGE_REF: opendatahub-operator
    env:
      IMAGE_REPO: opendatahub-operator
      RELEASE_VERSION: incubation
    workflow: opendatahub-io-ci-image-mirror
- as: opendatahub-operator-e2e
  steps:
    cluster_profile: gcp-opendatahub
    env:
      COMPUTE_NODE_TYPE: n2-standard-8
      OO_CHANNEL: fast
      OO_INSTALL_NAMESPACE: openshift-operators
      OO_PACKAGE: opendatahub-operator
      OO_TARGET_NAMESPACES: '!all'
    test:
    - as: e2e
      cli: latest
      commands: |
        unset GOFLAGS
        make e2e-test -e OPERATOR_NAMESPACE=openshift-operators
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 3Gi
    workflow: optional-operators-ci-gcp
- as: opendatahub-operator-upgrade
  steps:
    test:
    - as: install
      cli: latest
      commands: |
        export OPERATOR_NAMESPACE=opendatahub-operator-upgrade
        oc create namespace $OPERATOR_NAMESPACE
        operator-sdk run bundle -n $OPERATOR_NAMESPACE "$PREVIOUS_BUNDLE" # install operator with the version before upgrading
        oc wait --timeout=10m --for condition=Available -n $OPERATOR_NAMESPACE deployment opendatahub-operator-controller-manager # wait until operator is ready
      dependencies:
      - env: PREVIOUS_BUNDLE
        name: previous-bundle
    - as: upgrade
      cli: latest
      commands:
        export OPERATOR_NAMESPACE=opendatahub-operator-upgrade
        operator-sdk run bundle-upgrade --timeout=10m -n $OPERATOR_NAMESPACE "$OO_BUNDLE"
        sleep 5m
        oc wait --timeout=5m --for condition=Available -n $OPERATOR_NAMESPACE deployment opendatahub-operator-controller-manager
      dependencies:
      - env: OO_BUNDLE
        name: odho-bundle
      from: operator-sdk
      resources:
        requests:
          cpu: 2000m
          memory: 3Gi
zz_generated_metadata:
  branch: incubation
  org: opendatahub-io
  repo: opendatahub-operator
